<?php

/**
 * Special nfeya path:
 * order/%node - order processing forms (if GET[js] is set not themed contents returned)
 */
function toonf_menu() {
  $items['order/%node'] = array(
    'title callback' => 'nfeya_order_title',
    'title arguments' => array(1),
    'page callback' => 'nfeya_order',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK);
  return $items;
}


function toonf_block($op='list', $delta=0) {
   
  if($op=='list') {
    $blocks[0]['info']  = 'Подкатегории';
    $blocks[0]['cache'] = BLOCK_CACHE_PER_PAGE;//the block will be show only on category pages with subcategories, so there is not mush caches to store    
    //TODO: $blocks[0]['pages'] - определить какие таксономии имеют подкатегории, взять их алиасы и прописать сюда 
    return $blocks;
    
  } else if($op=='view') {
    
  $item = menu_get_item();
    if($item['page_callback']=='taxonomy_term_page') {
      $block['subject'] = 'Подкатегории';
      
      $str='';  $i=0;
      $tid  = $item['page_arguments'][0];//is termID
      $terms= taxonomy_get_children($tid);
      foreach ($terms as $term) {
        $i++; if($i>3)break;
        $str .= '      
            <div class="cwrap1 cats">
              <div class="head"><div></div></div>
              <div class="cont">
                <h6 class="title"><a href="$node_url">'.$term->name.'</a></h6>
                '.taxonomy_image_display($term->tid).'
              </div>
              <div class="bott"><div></div></div>
            </div>
            ';
      }
      $block['content'] = $str;

      
      return $block;
    }
    
    //taxonomy_get_children($tid, $vid = 0, $key = 'tid') : children array
    //$item = menu_get_item();
    //$node = menu_get_object();
    //$node->taxonomy;
    //
    //меню с категориями у нас уже есть, надо только зааяксить его загрузку
    //$menus = menu_get_menus();
  }
}


/**
 * Add price label and order button to node links
 */
function toonf_link($type, $node, $teaser = FALSE) {
	if($type=='node') {
		drupal_add_js('misc/jquery.form.js');
		$links = array();
		$links['order'] = array(
			'title'=>'купить',
			'href' =>"order/{$node->nid}",
			'query'=>'height=450&width=300',
			'attributes'=>array('class'=>'order thickbox', 'onClick'=>'orderProduct(this,1)'),
			'html'=> TRUE,
		);
		
		if($node->field_price[0]['value']) $links['price']=array('title'=>$node->field_price[0]['value'].' грн.');
		
		return $links;
	}
}

/**
 * Order forms and processing
 */
function nfeya_order($node) {
	//return print_r($node,1);
	if(!isset($_POST['contact'])) {
		$out = '<div class="TB_photos">'.theme_imagecache('prew',$node->field_photo[0]['filepath'],'фото продукта',$node->title).'</div>
			<form id="orderForm" action="/order/'.$node->nid.'" method="post"> 
			<div class="form-item">
				<label for="contact">Как мы можем с вами связаться?</label>
				<input type="text" id="contact" name="contact" onFocus="orderProductFormAjaxify(this,\'orderForm\')" size="43"/>
				<div class="description">например: Наталья 8(050)-000-00-00</div>
			</div>
			<div class="form-item">
				<label for="comment">Адрес доставки, комментарий:</label>
				<textarea id="comment" name="comment" cols="35" rows="5"></textarea>
				<div class="description">ваш комментарий к заказу (необязательно)</div>
			</div>
			<input type="submit" value="Отправить заказ" />
			<input type="button" value="Отменить" onClick="tb_remove();"/>
			</form>';
	drupal_add_js('misc/jquery.form.js');
	}  else {
		//<img src="/'.path_to_theme().'/i/thumbsup.jpg"/>
		$out = '<b>Спасибо! Ваш заказ принят.</b> Мы свяжемся с вами по указанным контактным данным.
		<div class="TB_photos">'.
			theme_imagecache('prew',$node->field_photo[0]['filepath'],'фото продукта',$node->title).
			'<img src="/'.path_to_theme().'/i/boxin2.jpg"/>
		</div>';
		watchdog('action', 'Заказ '.$node->nid.$node->title);
	}
	
	if($_GET['js']) die('<div id="wrapOrderForm">'.$out.'</div>');
	return $out;
}