<?php //call_me_back

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function call_me_back_help($path) {
	if($path=='admin/help#call_me_back') return "<p>Display call me back requests table with it's statuses.";
}

/////////////////////////////////////////////////////// PAGE //////////////////////////////////////////////////

/**
 * Implements hook_menu().
 */
function call_me_back_menu() {
	$items = array();
	$items['call-me-back'] = array(
		'title' => 'Call me back, please!',
		'page callback' => 'call_me_back_page',
		'type' => MENU_NORMAL_ITEM,
		'access callback' => TRUE
	);
	return $items;
}

function call_me_back_page() {
	//if form is submitted, call submit function and exit php
	if(isset($_POST['phone'])) {ajax_deliver(call_me_back_form_submit($_POST)); die;}
	
	//return full html or simple form code (it it's ajax request)
	$html = drupal_render(drupal_get_form('call_me_back_form'));
	if(isset($_GET['ajax'])) die($html);
	else return $html;
}

function call_me_back_form() {
	$form = array();
	$form['phone'] = array(
		'#type' => 'textfield',
		'#title'=> t('Phone'),
		'#size'	=> 60,
		'#required' => TRUE,
		'#maxlength'=> 13
	);
	$form['message'] = array(
		'#type'	=> 'textarea',
		'#title'=> t('Message'),
		'#description'	=> t('If you have something to say to us: maybe the time when we better call you or details about your question.'),
		'#default_value'=>'',
		'#prefix' => '<div id="replace_textfield_div">',
		'#suffix' => '</div>',
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value'=> t('Submit'),
		'#ajax' => array(
			'path' => 'call-me-back',
			'effect'=>'fade',
			'wrapper'=>'content',
			'method'=>'replace',
			'progress' => array('type' => 'throbber'),
		)
	);
	return $form;
}

function call_me_back_form_submit($form, &$form_state=null) {
	//if form_state not given - then this func is called from code manually and all values are in first argument
	if(!$form_state) $form_state = array('values'=>$form);
	$phone	= check_plain($form_state['values']['phone']);
	$msg	= check_plain($form_state['values']['message']);
	$ip		= $_SERVER['REMOTE_ADDR'];
	$replvar= array('@phone'=>$phone, '@message'=>$msg, '@ip'=>$ip);
	
	watchdog('Call Me Back', 'Tel.: @phone ("@message")', $replvar, WATCHDOG_INFO);
	return t('<div>Thank! And wait for a call.</div>');
}

/////////////////////////////////////////////////////// BLOCK /////////////////////////////////////////////////

/**
 * Implements hook_block_info().
 * Return info about available blocks.
 */
function call_me_back_block_info() {
	$blocks['call_me_back'] = array(
		'info' => t('Call Me Back button'),
		'cache'=> DRUPAL_CACHE_GLOBAL,
		'status'=> 0,
		'region'=>'header'
	);
	return $blocks;
}


/**
 * Implements hook_block_view().
 * Prepares the contents of the block.
 */
function call_me_back_block_view($delta='') {
	$block['subject'] = '';
	$block['content'] = theme('call_me_back_link');
	return $block;
}

/**
 * Implements hook_theme().
 */
function call_me_back_theme() {
	return array(
		'call_me_back_link' => array()
	);
}

/**
 * Returns just the link to cellback page.
 * Use your theme file named call-me-back-link.tpl.php to override this and make some fancy button if you want.	
 * @ingroup themeable
 */
function theme_call_me_back_link() {
	$html = '<a id="call-me-back" href="/call-me-back"	>'.t('Call me back').'</a>';
	$html.= '<script>jQuery("#call-me-back").attr("rel", "lightmodal[|width:500px; height:270px; scrolling: none;]").attr("href", "/call-me-back?ajax")</script>';
	return $html;
}